const bot1 = require('./afk')
const bot2 = require('./afk2')
const bot3 = require('./afk3')
const bot4 = require('./afk4')
const bot5 = require('./afk5')
const bot6 = require('./afk11')
const bot7 = require('./afk12') 